function [M, dot_theta_R, eR, eW] = attitude_control_coupled(R, W, ...
    theta_R, Rd, Wd, Wddot, k, param)

eR = 1 / 2 * vee(Rd' * R - R' * Rd);
eW = W - R' * Rd * Wd;
M = - k.R * eR ...
    - k.W * eW ...
    - param.W_R * theta_R ...
    + hat(R' * Rd * Wd) * param.J * R' * Rd * Wd ...
    + param.J * R' * Rd * Wddot;

dot_theta_R = param.gamma_R * param.W_R' * (eW + param.c2 * eR);
end