function [R_e, R_r] = get_Re_Rr(v, v_bar)

v_barTv = s(v_bar, v);

R_e = [hat(v_bar)*v / v_barTv, ...
    -(eye(3) - v_bar*v_bar')*v / v_barTv, ...
    v_bar];

R_r = [hat(v_bar)*v / v_barTv, ...
    (eye(3) - v*v')*v_bar / v_barTv, ...
    v];
end